name: Deploy react 
on: 
   push:
     branches:
       - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOKCER_USERNAME }} -p ${{ secrets.DOKCER_PASSWORD}}
      - run: docker build -t ahmedgamil/docker-react -f Dockerfile.dev . 
      - run: docker run -e CI=true ahmedgamil/docker-react npm run test
