name: Deploy-react

on:
  push:
    branches:
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ahmedgamil/react-app -f Dockerfile.dev
      - run: docker run -e CI=true ahmedgamil/react-app npm run test